version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - echo "Initializing Terraform..."
      - terraform init
      - terraform validate

      - echo "Destroying existing Terraform infrastructure..."
      - terraform destroy -auto-approve

      - echo "Applying Terraform changes..."
      - terraform apply -auto-approve